#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/stat.h>
#include <errno.h>

//Dylan Wright, Stephan Doan
//A function that generates a random int by reading in 4 bytes from /dev/random.
int getrandomint(int randfile) {
    int retval;
    read(randfile, &retval, 4);
    return retval;
}


//A main function that
int main() {
    
    printf("\n");
    
    //1. populates an array with 10 random numbers generated by your random function (print out each value)
    printf("Generating random numbers:\n");
    int randfile = open("/dev/random", O_RDONLY);
    int arr[10];
    int n = 0;
    while (n < 10) {
        arr[n] = getrandomint(randfile);
        n++;
    }
    int i = 0;
    while(i < 10) {
       printf("random %i: %i\n", i, arr[i]);
       i++;
    }
    close(randfile);
    printf("\n\n");
  
    
    //2. writes the array to a file
    printf("Writing numbers to file...\n\n");
    umask(0011);
    int holderfile = open("holder.txt", O_CREAT|O_WRONLY, 0666);
    write(holderfile, arr, 40);
    close(holderfile);
  
    
    //3. reads that file into a different array
    printf("Reading numbers from file...\n\n");
    int secarr[10];
    holderfile = open("holder.txt", O_RDONLY);
    read(holderfile, secarr, 40);
    close(holderfile);
    
    
    //4. prints out the contents of the second array to verify the random numbers are the same from step 1
    printf("Verification that written values were the same:\n");
    int j = 0;
    while(j < 10) {
       printf("random %i: %i\n", j, secarr[j]);
       j++;
    }
    printf("\n");
  
    return 0;
    
}

/*
Remember to use good practices, like checking return values for errors
Also remember to include a makefile that includes a run target (even though this is a single file program)
You should be able to read from the array without using a loop.
Make sure both team members' names are in the github directory name.
*/
